lib/skyjo_web/router.ex
defmodule SkyjoWeb.Router do
  use SkyjoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SkyjoWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SkyjoWeb do
    pipe_through :browser

    get "/", HomeController, :index
    get "/create", HomeController, :create
    get "/join", HomeController, :join
    get "/rules", RulesController, :index

    live "/play/:code", PlayLive, :index
    live "/cast", SpectateLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SkyjoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SkyjoWeb.Telemetry
    end
  end
end

lib/skyjo_web/controllers/home_controller.ex
defmodule SkyjoWeb.HomeController do
  use SkyjoWeb, :controller

  alias Skyjo.{Game, Games}

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def create(conn, _params) do
    %Game{players: [player]} = game = Games.create()
    conn |> redirect(to: "/play/#{game.code}?player=#{player.code}")
  end

  def join(conn, %{"code" => code}) do
    code = String.upcase(code)

    case Game.join(code) do
      {:ok, {player, game}} ->
        conn |> redirect(to: "/play/#{game.code}?player=#{player.code}")

      {:error, :code_missing} ->
        conn |> put_flash(:error, "Join Code is required") |> redirect(to: "/")

      {:error, :game_missing} ->
        conn |> put_flash(:error, "No game found for that Join Code") |> redirect(to: "/")

      {:error, :game_in_progress} ->
        conn |> put_flash(:error, "Game is in progress") |> redirect(to: "/")

      {:error, :full_game} ->
        conn |> put_flash(:error, "Game is full") |> redirect(to: "/")
    end
  end

  def join(conn, _) do
    conn |> put_flash(:error, "Join Code is required") |> redirect(to: "/")
  end
end

lib/skyjo_web/views/home_view.ex
defmodule SkyjoWeb.HomeView do
  use SkyjoWeb, :view

  def card_style(i) do
    degrees = 360 / 15 * (i + 2)
    radians = degrees / 180 * :math.pi()
    x = :math.cos(radians)
    y = :math.sin(radians)
    "top:#{250 + x * -150}px;left:#{y * 130 - 55}px;transform:rotate(#{degrees}deg);"
  end
end

lib/skyjo_web/templates/home/index.html.eex
<div id="home">
  <div class="card-circle-holder">
    <div class="card-circle">
      <%= for i <- 12..-2 do %>
        <div class="card n<%= i %>" style="<%= card_style(i) %>">
          <span><%= i %></span>
          <span><%= i %></span>
          <span><%= i %></span>
        </div>
      <% end %>
    </div>
  </div>
  <h1>SkyJo</h1>
  <div class="grow">
  </div>
  <div class="buttons">
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <%= link "Create Game", to: Routes.home_path(@conn, :create), class: "btn" %>
    <div>or</div>
    <%= form_for @conn, Routes.home_path(@conn, :join), [method: :get], fn f -> %>
      <%= text_input f, :code, placeholder: "ABCD", maxlength: 4 %>
      <%= submit "Join Game" %>
    <% end %>
    <%= link "How To Play", to: Routes.rules_path(@conn, :index) %>
  </div>
</div>

lib/skyjo_web/templates/home/index.html.heex
<div id="home">
  <div class="card-circle-holder">
    <div class="card-circle">
      <%= for i <- 12..-2 do %>
        <div class={"card n#{i}"} style={card_style(i)}>
          <span><%= i %></span>
          <span><%= i %></span>
          <span><%= i %></span>
        </div>
      <% end %>
    </div>
  </div>
  <h1>SkyJo</h1>
  <div class="grow">
  </div>
  <div class="buttons">
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <%= link "Create Game", to: Routes.home_path(@conn, :create), class: "btn" %>
    <div>or</div>
    <%= form_for @conn, Routes.home_path(@conn, :join), [method: :get], fn f -> %>
      <%= text_input f, :code, placeholder: "ABCD", maxlength: 4 %>
      <%= submit "Join Game" %>
    <% end %>
    <%= link "How To Play", to: Routes.rules_path(@conn, :index) %>
  </div>
</div>